# Generated by Django 4.2 on 2023-05-19 08:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0004_category_subscribers'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_en_us',
            field=models.CharField(help_text='Имя категории', max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ru',
            field=models.CharField(help_text='Имя категории', max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='subscribers_en_us',
            field=models.ManyToManyField(null=True, related_name='categories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='category',
            name='subscribers_ru',
            field=models.ManyToManyField(null=True, related_name='categories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='author_en_us',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news.author'),
        ),
        migrations.AddField(
            model_name='post',
            name='author_ru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news.author'),
        ),
        migrations.AddField(
            model_name='post',
            name='categoryType_en_us',
            field=models.CharField(choices=[('NW', 'Новость'), ('AR', 'Статья')], default='AR', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='categoryType_ru',
            field=models.CharField(choices=[('NW', 'Новость'), ('AR', 'Статья')], default='AR', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='postCategory_en_us',
            field=models.ManyToManyField(null=True, through='news.PostCategory', to='news.category'),
        ),
        migrations.AddField(
            model_name='post',
            name='postCategory_ru',
            field=models.ManyToManyField(null=True, through='news.PostCategory', to='news.category'),
        ),
        migrations.AddField(
            model_name='post',
            name='rating_en_us',
            field=models.SmallIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='rating_ru',
            field=models.SmallIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='text_en_us',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='text_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_en_us',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_ru',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(help_text='Имя категории', max_length=64, unique=True),
        ),
        migrations.CreateModel(
            name='PostCategory_ru',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryTrough', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.category')),
                ('postTrough', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.post')),
            ],
            options={
                'verbose_name': 'post category [ru]',
                'verbose_name_plural': 'post categorys [ru]',
                'db_table': 'news_postcategory_ru',
                'db_tablespace': '',
                'auto_created': False,
            },
        ),
        migrations.CreateModel(
            name='PostCategory_en_us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryTrough', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.category')),
                ('postTrough', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.post')),
            ],
            options={
                'verbose_name': 'post category [en-us]',
                'verbose_name_plural': 'post categorys [en-us]',
                'db_table': 'news_postcategory_en_us',
                'db_tablespace': '',
                'auto_created': False,
            },
        ),
    ]
