# Generated by Django 4.2 on 2023-05-19 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_category_name_en_us_category_name_ru_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postcategory_ru',
            name='categoryTrough',
        ),
        migrations.RemoveField(
            model_name='postcategory_ru',
            name='postTrough',
        ),
        migrations.RemoveField(
            model_name='category',
            name='subscribers_en_us',
        ),
        migrations.RemoveField(
            model_name='category',
            name='subscribers_ru',
        ),
        migrations.RemoveField(
            model_name='post',
            name='author_en_us',
        ),
        migrations.RemoveField(
            model_name='post',
            name='author_ru',
        ),
        migrations.RemoveField(
            model_name='post',
            name='categoryType_en_us',
        ),
        migrations.RemoveField(
            model_name='post',
            name='categoryType_ru',
        ),
        migrations.RemoveField(
            model_name='post',
            name='postCategory_en_us',
        ),
        migrations.RemoveField(
            model_name='post',
            name='postCategory_ru',
        ),
        migrations.RemoveField(
            model_name='post',
            name='rating_en_us',
        ),
        migrations.RemoveField(
            model_name='post',
            name='rating_ru',
        ),
        migrations.DeleteModel(
            name='PostCategory_en_us',
        ),
        migrations.DeleteModel(
            name='PostCategory_ru',
        ),
    ]
