# Generated by Django 4.2 on 2023-05-19 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_remove_postcategory_ru_categorytrough_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='categoryType_en_us',
            field=models.CharField(choices=[('NW', 'Новость'), ('AR', 'Статья')], default='AR', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='categoryType_ru',
            field=models.CharField(choices=[('NW', 'Новость'), ('AR', 'Статья')], default='AR', max_length=2, null=True),
        ),
    ]
