# Generated by Django 4.2 on 2023-05-19 10:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0007_post_categorytype_en_us_post_categorytype_ru'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='subscribers',
            field=models.ManyToManyField(default=None, related_name='categories', to=settings.AUTH_USER_MODEL),
        ),
    ]
